[project]
name = "organizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.52.2",
    "streamlit-sortables>=0.3.1",
    "openai>=1.0.0",
]
